[phases.setup]
nixPkgs = ['python310']

[phases.install]
cmds = ['pip install -r requirements-deploy.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'python manage.py migrate && gunicorn claplog.wsgi:application --bind 0.0.0.0:$PORT'